apiVersion: apps/v1
kind: Deployment
metadata:
  name: carro-deployment   # Nome do deployment
  namespace: dev
spec:
  replicas: 2   # Número desejado de réplicas do frontend
  selector:
    matchLabels:
      app: carro
  template:
    metadata:
      labels:
        app: carro
    spec:
      containers:
      - name: carro
        image: marciohc/kubedev:latest   # Imagem do Nginx a ser utilizada
        ports:
        - containerPort: 80   # Porta onde o Nginx está servindo

        