apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment   # Nome do deployment
  namespace: nginx-frontend
spec:
  replicas: 2   # Número desejado de réplicas do frontend
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest   # Imagem do Nginx a ser utilizada
        ports:
        - containerPort: 80   # Porta onde o Nginx está servindo