name: CI-CD

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Construção da Inagem Docker
        run: echo "Docker Build"
      - name: "Publicar a imagem Docker Hub"
        run: echo "Docker push"

  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Conectar com Kubernetes
        run: echo "Configuração do Kubeconfig"
      - name: "Executar o deploy "
        run:  echo "Kubectl apply"



  

    
