name: CI-CD

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout do repositorio
      - name: Autenticação no docker
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Construção da imagem Docker
        uses: docker/build-push-action@v5.3.0
      
        with:
          context: ./site
          file: ./Dockerfile
          push: true
          tags: |
            marciohc/kubedev:latest
            marciohc/kubedev:${{github.run_number}}
      
        

  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest


      -  name: Setup Minikube
         uses: azure/setup-minikube@v1

      - name: Set Kubernetes context to Minikube
        run: kubectl config use-context minikube

      - name: Apply Kubernetes resources
        run: |
          kubectl apply -f ./k8s/deploy.yaml

      - name: Check deployment status
        run: kubectl get pods

        





    
