name: CI-CD

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout do repositorio
      - name: Autenticação no docker
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Construção da imagem Docker
        uses: docker/build-push-action@v5.3.0
      
        with:
          context: ./site
          file: ./dockerfile
          push: true
          tags: |
            marciohc/kubedev:latest
            marciohc/kubedev:${{github.run_number}}
      
        

  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Conectar com Kubernetes
        run: echo "Configuração do Kubeconfig"
      - name: "Executar o deploy "
        run:  echo "Kubectl apply"




  

    
